### ISSUE TITLE
nokogiri/rake task question

### ISSUE THREAD

**Issue by wbarbee** [wbarbee/column_app#9]
@WilliamfShaw @harimohanraj89 @DrRobotmck @bigtone1284 

I've started on this nokogiri stuff and have begun work on a rake task within the lib/tasks directory. 

```
desc "Fetch game of thrones recap"
task :fetch_got_recap => :environment do
  require 'nokogiri'
  require 'open-uri'

Article.new(nil).each do |recap|
  url = 'http://www.vulture.com/2015/05/game-of-thrones-recap-season-5-episode-4.html'
  recap = Nokogiri::HTML(open(url))
  recap.at_css('#primary').each do |item|
    title = item.css('h1').text.strip
    author = item.at_css('.story-author').text.strip
    date = item.css('time')[0].text.strip
    content = item.css('p').text.strip
    catgory = item.css('a')[20]
    end
  end
end
```

i'm trying to find out how to insert this information into a new instance of my articles model, which looks like this:
```    
t.string    :title
      t.string    :date
      t.string    :category
      t.text      :content
      t.string    :authors
      # t.text      :img_urls
      t.string    :article_url
```

i test it out by running ```rake fetch_got_recap``` and it's not liking the ```.each```, but i'm wondering if that
Article.new is going in the direction that I want (to eventually add the article a user's account)?

hopefully no need for you to get up

**Comment by DrRobotmck** [comment]
So it looks like you are trying to call each to iterate over an Article instance, which I am fairly certain you cannot do. You might try taking the code for nokogiri out of the first each block, and once you have retrieved the information through nokogiri, use the resulting data to create a new Article.
